### ISSUE TITLE
Syntax error macroexpanding clojure.core/ns...

### ISSUE THREAD

**Issue by psdp** [223kazuki/clj-graphql-server#1]
Hi, I am a Clojure newbie trying to play around with this project. Thanks for creating this project and making it open source!
I followed README instruction step by step, but I could not get this project up and running, this error below showed every time after I typed `(dev)...(go)` in REPL. Much appreciate if you can help me out on this.

```
Syntax error macroexpanding clojure.core/ns at (base64_vlq.clj:1:1).
((require [clojure.string :as string] [cljs.source-map.base64 :as base64])) - failed: Extra input spec: :clojure.core.specs.alpha/ns-form
```

**Comment by 223kazuki** [comment]
Hi, thanks for coming across this repository.
I can't reproduce this issue in my environment... Do you have any additional dependencies or plugins in `~/.lein/profiles.clj`?
I updated README just now. So please try again and let me know if it reproduces again.

**Comment by psdp** [comment]
You're right! I have added this dependency `[org.clojure/tools.nrepl "0.2.12"]` in my `.lein/profiles.clj`, it works now by removing all dependencies in my `.lein/profiles.clj`.


BTW I think it is worth mentioning that you need to create a database before starting the server. Otherwise, you will get the following error:

```
Execution error at datomic.peer/get-connection$fn (peer.clj:678).
Could not find graphql_server in catalog
```

To fix this above:
```
(require '[datomic.api :as d])
(def db-uri "datomic:dev://localhost:4334/graphql_server")
(d/create-database db-uri)
```

**Comment by 223kazuki** [comment]
Thank you for your feedback.
I changed it to create database if it doesn't exist.

https://github.com/223kazuki/clj-graphql-server/commit/13716d7f65e1f2d84b974ec667825d18422981ac

**Comment by psdp** [comment]
Cool. Thanks! Closing this issue now.
